<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KsefIntegration\KsefIntegration.csproj" />
  </ItemGroup>
</Project>
